server:
  port: 8080
spring:
  application:
    name: 'Medicines vendor'
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:mem:test_db'
    username: 'sa'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
